### ISSUE TITLE
Add a way to get a localized grid

### ISSUE THREAD

**Issue by cfr-op10** [OPTEN/Opten.Umbraco.Localization#13]
Some developers want to have a whole grid localized. The current way is something like:

`@Html.GetGridHtml(Model.Content, "homepageGrid_" + Request.GetCurrentUICulture().TwoLetterISOLanguageName)`

Would it make sense to have a method like `@Model.Content.GetLocalizedGrid()`?

**Comment by cfr-op10** [comment]
plus add it to the readme

**Comment by severindheureuse** [comment]
implemented in Version 1.6.0

usage:
`@Html.GetLocalizedGridHtml(Model.Content);`
`@Model.Content.GetLocalizedGridHtml(Html);`
