### ISSUE TITLE
Select language new node

### ISSUE THREAD

**Issue by wdaniel1993** [OPTEN/Opten.Umbraco.Localization#16]
The language chooser is not available on node creation. if there are fields that are required, there is no chance to save the node without changing the selected language in another node.

**Comment by severindheureuse** [comment]
You can edit the opten.localization.config.json in the config folder to allow the language chooser on node creation. 

Just remove  ng-if=\"menu.currentNode\" on line 18.

I will publish a new version with this fixed for everyone.

**Comment by severindheureuse** [comment]
fixed with version 1.9
